import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/component/Header'
import Footer from '@/app/footer/Footer'
import FilterProvider from '@/context/filterProductProvider'
import ProductProvider from '@/context/ProductProvider'
import CartProvider from '@/context/cartProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='  overflow-x-hidden'>
      <body className={inter.className}>
        <ProductProvider>
          <FilterProvider>
            <CartProvider>
            <main className='sm:mx-[30px] md:mx-[130px]'>
              <Header />

              {children}

            </main>
              </CartProvider>
          </FilterProvider>
        </ProductProvider>
        <Footer />
      </body>
    </html>
  )
}
